{% set version = '1.2-8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-agricolae
  version: {{ version|replace("-", "_") }}

source:
  fn: agricolae_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/agricolae_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/agricolae/agricolae_{{ version }}.tar.gz
  sha256: 09f12a1ad62483bfbe70e5c8f419357aeb9d984bfb563b281ce35295a528d6b0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-algdesign
    - r-mass
    - r-cluster
    - r-klar
    - r-nlme
    - r-spdep
  run:
    - r-base
    - r-algdesign
    - r-mass
    - r-cluster
    - r-klar
    - r-nlme
    - r-spdep

test:
  commands:
    - $R -e "library('agricolae')"           # [not win]
    - "\"%R%\" -e \"library('agricolae')\""  # [win]

about:
  home: http://tarwi.lamolina.edu.pe/~fmendiburu
  license: GPL
  summary: Original idea was presented in the thesis "A statistical analysis tool for agricultural
    research" to obtain the degree of Master on science, National Engineering University
    (UNI), Lima-Peru. Some experimental data for the examples come from the CIP and
    others research. Agricolae offers extensive functionality on experimental design
    especially for agricultural and plant breeding experiments, which can also be useful
    for other purposes. It supports planning of lattice, Alpha, Cyclic, Complete Block,
    Latin Square, Graeco-Latin Squares, augmented block, factorial, split and strip
    plot designs. There are also various analysis facilities for experimental data,
    e.g. treatment comparison procedures and several non-parametric tests comparison,
    biodiversity indexes and consensus cluster.
  license_family: GPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
