appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xcenwlzOZ4lHQzKHG03lx7rkMegG8wPA9usYSCTEqSoJHKOs1h8rLz7CkDTK+DU0Xsesdg6pgt59MFZjFeBaIunK1hIYLUHFsW7WufkNQHVBVkE787swgL0m3R4ezjhUEnrrDWdSPwZTrOtteCJ6lJ4D0qKLdqR2YAJXzIIuU9NbSnaIMEFYCRjr4MAyOhsQ9dJ1M54Eaf798UikfZTnmqvGVxBB2CQMyogFYnTFSIxpScqXdX+KP2swdYM/bMApyvdP0zmKoH748up7j8EIibSFdfdG+ivNIzWkaMnb9+cSXO7vxVG0HZGITfGILYRhEPG5NSXSh/6kl2g3O5AjVtK4WFTz0hQJofv/rIaBDkHeqUX8o/9l1vzZtMyVoVsxs5W2sqoNQzJ5C+eFoE1ZQmmtO1Hghc22AHC+wqfZ3uZUq7nOkFZLA/9FDq8cRLupljI73Sx5OQvU82tWZ3NZERYZL5PaSGbCNI4Z+r81bCMG98ZzjhhcP2PyuqDIsY3O2zrYBL8WCszlc+IcP5zbA3301V4vtbzSqLnP/ifzXAQuxsxM8jlk8Eqa3Z1dytwzIKvZZYYpW3SvOpYRb6IuXsuFe6Ew7oBcXqnGvU36XANaHD2rURe8SobpT+0cTIqT1kOXrWYkkTgFv7uk8KqjhYtbH+SP0fiNsKODN2heHbY=}
